package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Bean.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Bean extends ToppingDecorator
{
	Bean(){
		myStr = "Bean";
	}
	
	public void addTopping()
	{
		myToppings.add(myStr);
		price += 500;
	}
}
