package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : DoubleCheese.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class DoubleCheese extends ToppingDecorator
{
	public DoubleCheese(Food food){
		this.myToppings = food.myToppings;
		this.price = food.price;
		myStr = "DoubleCheese";
		addTopping();
	}
	
	public void addTopping()
	{
		myToppings.add(myStr);
		price += 500;
	}
}
