package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : FishCutlet.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class FishCutlet extends ToppingDecorator
{
	public FishCutlet(Food food){
		this.name = food.name;
		this.flavor = food.flavor;
		this.price = food.price;
		this.myToppings = food.myToppings;
		myStr = "FishCutlet";
		addTopping();
	}
	
	public void addTopping()
	{
		myToppings.add(myStr);
		price += 1000;
	}
}
