package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : FlavorDecorator.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public abstract class FlavorDecorator extends FoodDecorator
{
	public String name;
	
	public void setFlavor()
	{
	
	}
}
