//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FoodDecorator.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class FoodDecorator extends Food
{
	public abstract void addTopping();
	public abstract void setFlavor();
}
