package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : FoodDecorator.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public abstract class FoodDecorator extends Food
{
	String myStr;
}
