//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Food.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class Food
{
	public String name;
	public String flavor;
	public int price;
	public ToppingDecorator availableTopping;
}
