package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Guacamole.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Guacamole extends ToppingDecorator
{
	public Guacamole(Food food){
		this.myToppings = food.myToppings;
		this.price = food.price;
		myStr = "Guacamole";
		addTopping();
	}
	
	public void addTopping()
	{
		myToppings.add(myStr);
		price += 1500;
	}
}
