package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Mild.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Mild extends FlavorDecorator
{	
	Mild(){
		myStr = "Mild";
	}
	
	public void setFlavor()
	{
		this.flavor = myStr;
	}
}
