//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mild.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class Mild extends FlavorDecorator
{
	public void addTopping()
	{
	
	}
	
	public void setFlavor()
	{
	
	}
}
