package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : MozzarellaCheese.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class MozzarellaCheese extends ToppingDecorator
{
	public MozzarellaCheese(Food food){
		this.myToppings = food.myToppings;
		this.price = food.price;
		myStr = "MozzarellaCheese";
		addTopping();
	}
	
	public void addTopping()
	{
		myToppings.add(myStr);
		price += 1000;
	}
}
