//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class Order
{
	public int orderID;
	public SelectedFood purchasedFoods;
	public int totalPrice;
	public Payment payment;
	public Date date;
}
