package model;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Order.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Order
{
	public int orderID;
	public SelectedFood purchasedFoods;
	public int totalPrice;
	public Payment payment;
	public Date date;
}
