package model;

import java.util.Date;
import java.util.LinkedList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Order.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Order
{
	public int orderID;
	public LinkedList<SelectedFood> purchasedFoods;
	public int totalPrice;
	public Payment payment;
	public Date date;
	
	public Order(int orderID, LinkedList<SelectedFood> finalCart, int totalPrice, Payment payment, Date date) {
		this.orderID = orderID;
		this.purchasedFoods = finalCart;
		this.totalPrice = totalPrice;
		this.payment = payment;
		this.date = date;
	}
}
