//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Payment.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class Payment
{
	public String name;
	public PaymentDevice device;
}
