package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Payment.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Payment
{
	public String name;
	public PaymentDevice device;
}
