//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PaymentDevice.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class PaymentDevice
{
	public boolean ACK;
}
