package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : PaymentDevice.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class PaymentDevice
{
	public boolean ACK;
}
