package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : PeanutButter.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class PeanutButter extends ToppingDecorator
{
	PeanutButter(Food food){
		this.myToppings = food.myToppings;
		myStr = "PeanutButter";
		addTopping();
	}
	
	public void addTopping()
	{
		myToppings.add(myStr);
	}
}
