package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Pineapple.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Pineapple extends ToppingDecorator
{
	Pineapple(){
		myStr = "Pineapple";
	}
	
	public void addTopping()
	{
		myToppings.add(myStr);
		price += 500;
	}
}
