//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SelectedFood.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class SelectedFood
{
	public Object name: String;
	public String flavor;
	public Object price: int;
	public Object count: int;
	public ToppingDecorator selectedTopping;
}
