package model;

import java.util.LinkedList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : SelectedFood.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class SelectedFood
{
	public String name;
	public String flavor;
	public int price;
	public int count;
	public LinkedList<String> selectedTopping;
}
