package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Tomato.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Tomato extends ToppingDecorator
{
	public Tomato(Food food){
		this.name = food.name;
		this.flavor = food.flavor;
		this.price = food.price;
		this.myToppings = food.myToppings;
		myStr = "Tomato";
		addTopping();
	}
	
	public void addTopping()
	{
		myToppings.add(myStr);
		price += 500;
	}
}
