package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : ToppingDecorator.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public abstract class ToppingDecorator extends FoodDecorator
{
	public String name;
	public int price;
	
	public void addTopping()
	{
	
	}

}
