package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : WedgePotato.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class WedgePotato extends ToppingDecorator
{
	public void addTopping()
	{
	
	}
	
	public void setFlavor()
	{
	
	}
}
