package controller;

import model.SelectedFood;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Buy.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Buy implements Command
{
	public SelectedFood[] finalCart;
	public OrderController controlOrder;
	
	public void putInCart()
	{
	
	}
	
	public boolean purchase(SelectedFood[] finalCart)
	{
		return true;
	}

	@Override
	public void execute() {
		// TODO Auto-generated method stub
		
	}
}
