//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CartController.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class CartController
{
	public SelectedFood currentCart;
	public void addSelectedFood()
	{
	
	}
	
	public void deleteSelectedFood()
	{
	
	}
	
	public void modifySelectedFood()
	{
	
	}
}
