package controller;

import model.SelectedFood;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : CartController.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class CartController
{
	public SelectedFood[] currentCart;
	
	public void addSelectedFood()
	{
	
	}
	
	public void deleteSelectedFood()
	{
	
	}
	
	public void modifySelectedFood()
	{
	
	}
}
