package controller;

import java.util.LinkedList;

import model.Food;
import model.SelectedFood;
import model.ToppingDecorator;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Command.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public interface Command {
	public void execute();
	public boolean execute(LinkedList<SelectedFood> finalCart);
	public SelectedFood execute(Food food);
	public SelectedFood execute(ToppingDecorator topping);
}
