//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Command.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class Command
{
	public void execute()
	{
	
	}
}
