package controller;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Command.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public interface Command {
	public void execute();
}
