//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MenuController.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class MenuController implements Command
{
	public Food menu;
	public void getMenu()
	{
	
	}
	
	public void setMenu()
	{
	
	}
	
	public void modifyFood()
	{
	
	}
	
	public void addFood()
	{
	
	}
	
	public void deleteFood()
	{
	
	}
}
