package controller;

import model.Food;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : MenuController.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class MenuController implements Command
{
	public Food[] menu;
	
	public void getMenu()
	{
	
	}
	
	public void setMenu()
	{
	
	}
	
	public void modifyFood()
	{
	
	}
	
	public void addFood()
	{
	
	}
	
	public void deleteFood()
	{
	
	}

	@Override
	public void execute() {
		// TODO Auto-generated method stub
		
	}
}
