package controller;

import java.util.LinkedList;

import model.Food;
import model.SelectedFood;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : MenuController.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class MenuController implements Command
{
	private LinkedList<Food> menu;
	
	MenuController(){
		menu = new LinkedList<Food>();
	}
	
	public LinkedList<Food> getMenu()
	{
		return this.menu;
	}
	
	public void setMenu()
	{
		
	}
	
	public void modifyFood(Food modifyFood)
	{
		int whereModify;
		whereModify = menu.indexOf(modifyFood);
	
		Food tmpFood = menu.get(whereModify);
		
		/*
		 * the modifying logic will be updated, with view interaction
		 */
	}
	
	public void addFood(Food newFood)
	{
		menu.addLast(newFood);
	}
	
	public void deleteFood(Food deleteFood)
	{
		menu.remove(deleteFood);
	}

	@Override
	public void execute() {
		// TODO Auto-generated method stub
		
	}
}
