//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderController.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class OrderController
{
	public Order orderList;
	public void appendOrder()
	{
	
	}
	
	public void removeOrder()
	{
	
	}
}
