package controller;

import model.Order;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : OrderController.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class OrderController
{
	public Order[] orderList;
	
	public void appendOrder()
	{
	
	}
	
	public void removeOrder()
	{
	
	}
}
