//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PaymentController.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class PaymentController
{
	public Payment paymentList;
	public void addPayment()
	{
	
	}
	
	public void deletePayment()
	{
	
	}
}
