package controller;

import model.Payment;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : PaymentController.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class PaymentController
{
	public Payment[] paymentList;
	
	public void addPayment()
	{
	
	}
	
	public void deletePayment()
	{
	
	}
}
