//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Purchase.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class Purchase
{
	public int totalPrice;
	public Payment payment;
	public boolean successFlag;
	public void getCurrentCart()
	{
	
	}
	
	public void calculateTotalPrice()
	{
	
	}
	
	public void choosePayment()
	{
	
	}
	
	public boolean tryPurchase(Object int totalPrice)
	{
	
	}
}
