package controller;

import model.Payment;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Purchase.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Purchase
{
	public int totalPrice;
	public Payment payment;
	public boolean successFlag;
	
	public void getCurrentCart()
	{
	
	}
	
	public void calculateTotalPrice()
	{
	
	}
	
	public void choosePayment()
	{
	
	}
	
	public boolean tryPurchase(int totalPrice)
	{
		return true;
	}
}
