//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ranking.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class Ranking
{
	public HashTable ranking;
	public void sortRanking()
	{
	
	}
}
