package controller;

import java.util.Hashtable;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Ranking.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Ranking
{
	public Hashtable ranking;
	
	public void sortRanking()
	{
	
	}
}
