package controller;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : RecordSales.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class RecordSales
{
	public void record()
	{
	
	}
}
