//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RecordSales.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class RecordSales
{
	public void record()
	{
	
	}
}
