package controller;

import java.util.LinkedList;

import model.Food;
import model.SelectedFood;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Refund.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Refund implements Command
{
	public void sendRequest()
	{
	
	}
	
	public boolean checkACK()
	{
		return true;
	}

	@Override
	public void execute() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public boolean execute(LinkedList<SelectedFood> finalCart) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public SelectedFood execute(Food food) {
		// TODO Auto-generated method stub
		return null;
	}
}
