package controller;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : Refund.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class Refund implements Command
{
	public void sendRequest()
	{
	
	}
	
	public boolean checkACK()
	{
		return true;
	}

	@Override
	public void execute() {
		// TODO Auto-generated method stub
		
	}
}
