package view;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : KioskDevice.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class KioskDevice extends JFrame {

	private JPanel contentPane;
	
	private JPanel panelFood;
	private JLabel lblFood;
	private JLabel lblChickenBurrito, lblBeefBurrito, lblMixBurrito, lblFrenchFried, lblOnionRing, lblNachoChips, lblSoda, lblBeer, lblCoke;
	private JTextField chickenCntTextField, beefCntTextField, mixCntTextField, friedCntTextField, ringCntTextField, nachoCntTextField, cokeCntTextField, sodaCntTextField, beerCntTextField;
	private JButton chickenUpBtn, beefUpBtn, mixUpBtn, friedUpBtn, ringUpBtn, nachoUpBtn, cokeUpBtn, sodaUpBtn, beerUpBtn;
	private JButton chickenDownBtn, beefDownBtn, mixDownBtn, friedDownBtn, ringDownBtn, nachoDownBtn, cokeDownBtn, sodaDownBtn, beerDownBtn;
	
	private JPanel panelFlavor;
	private JLabel lblFlavor;
	private JLabel lblChickenMild, lblChickenSpicy, lblChickenVerySpicy, lblBeefMild, lblBeefSpicy, lblBeefVerySpicy, lblMixMild, lblMixSpicy, lblMixVerySpicy;
	private JTextField chickenMildCntTextField, chickenSpicyCntTextField, chickenVerySpicyCntTextField, beefMildCntTextField, beefSpicyCntTextField, beefVerySpicyCntTextField, mixMildCntTextField, mixSpicyCntTextField, mixVerySpicyCntTextField;
	private JButton chickenMildUpBtn, chickenSpicyUpBtn, chickenVerySpicyUpBtn, beefMildUpBtn, beefSpicyUpBtn, beefVerySpicyUpBtn, mixMildUpBtn, mixSpicyUpBtn, mixVerySpicyUpBtn;
	private JButton chickenMildDownBtn, chickenSpicyDownBtn, chickenVerySpicyDownBtn, beefMildDownBtn, beefSpicyDownBtn, beefVerySpicyDownBtn, mixMildDownBtn, mixSpicyDownBtn, mixVerySpicyDownBtn;
	
	private JPanel panelTopping;
	private JLabel lblTopping;

	private JButton btnAdminLogin;
	private JButton btnOrder;
	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					KioskDevice frame = new KioskDevice();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	public void showOrderResult()
	{
	
	}
		
	public void showRefundResult()
	{
	
	}
	
	/**
	 * Create the frame.
	 */
	public KioskDevice() {
		
		setTitle("Kiosk Device");
		setBounds(100, 100, 784, 439);
		setResizable(false);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		contentPane = new JPanel();
		contentPane.setLayout(null);
		setContentPane(contentPane);
		
		btnAdminLogin = new JButton("Admin Login");
		btnAdminLogin.setBounds(642, 6, 117, 29);
		contentPane.add(btnAdminLogin);
		
		panelFood = new JPanel();
		panelFood.setLayout(null);
		panelFood.setBounds(19, 44, 278, 299);
		contentPane.add(panelFood);
		
		lblFood = new JLabel("Menu");
		lblFood.setBounds(113, 10, 48, 16);
		panelFood.add(lblFood);
		
		lblChickenBurrito = new JLabel("Chicken Burrito(3000won)");
		lblChickenBurrito.setBounds(6, 38, 175, 16);
		panelFood.add(lblChickenBurrito);
		
		lblBeefBurrito = new JLabel("Beef Burrito(3000won)");
		lblBeefBurrito.setBounds(6, 66, 154, 16);
		panelFood.add(lblBeefBurrito);
		
		lblMixBurrito = new JLabel("Mix Burrito(3000won)");
		lblMixBurrito.setBounds(6, 94, 140, 16);
		panelFood.add(lblMixBurrito);
		
		lblFrenchFried = new JLabel("French Fried(2000won)");
		lblFrenchFried.setBounds(6, 122, 154, 16);
		panelFood.add(lblFrenchFried);
		
		lblOnionRing = new JLabel("Onion Ring(2000won)");
		lblOnionRing.setBounds(6, 150, 140, 16);
		panelFood.add(lblOnionRing);
		
		lblNachoChips = new JLabel("Nacho Chips(2000won)");
		lblNachoChips.setBounds(6, 178, 154, 16);
		panelFood.add(lblNachoChips);
		
		lblCoke = new JLabel("Coke(1000won)");
		lblCoke.setBounds(6, 206, 102, 16);
		panelFood.add(lblCoke);
		
		lblSoda = new JLabel("Soda(1000won)");
		lblSoda.setBounds(6, 235, 102, 16);
		panelFood.add(lblSoda);
		
		lblBeer = new JLabel("Beer(2000won)");
		lblBeer.setBounds(6, 263, 102, 16);
		panelFood.add(lblBeer);
		
		chickenCntTextField = new JTextField();
		chickenCntTextField.setText("0");
		chickenCntTextField.setEditable(false);
		chickenCntTextField.setColumns(10);
		chickenCntTextField.setBounds(177, 33, 31, 26);
		panelFood.add(chickenCntTextField);
		
		beefCntTextField = new JTextField();
		beefCntTextField.setText("0");
		beefCntTextField.setEditable(false);
		beefCntTextField.setColumns(10);
		beefCntTextField.setBounds(177, 61, 31, 26);
		panelFood.add(beefCntTextField);
		
		mixCntTextField = new JTextField();
		mixCntTextField.setText("0");
		mixCntTextField.setEditable(false);
		mixCntTextField.setColumns(10);
		mixCntTextField.setBounds(177, 89, 31, 26);
		panelFood.add(mixCntTextField);
		
		friedCntTextField = new JTextField();
		friedCntTextField.setText("0");
		friedCntTextField.setEditable(false);
		friedCntTextField.setColumns(10);
		friedCntTextField.setBounds(177, 117, 31, 26);
		panelFood.add(friedCntTextField);
		
		ringCntTextField = new JTextField();
		ringCntTextField.setText("0");
		ringCntTextField.setEditable(false);
		ringCntTextField.setColumns(10);
		ringCntTextField.setBounds(177, 145, 31, 26);
		panelFood.add(ringCntTextField);
		
		nachoCntTextField = new JTextField();
		nachoCntTextField.setText("0");
		nachoCntTextField.setEditable(false);
		nachoCntTextField.setColumns(10);
		nachoCntTextField.setBounds(177, 173, 31, 26);
		panelFood.add(nachoCntTextField);
		
		cokeCntTextField = new JTextField();
		cokeCntTextField.setText("0");
		cokeCntTextField.setEditable(false);
		cokeCntTextField.setColumns(10);
		cokeCntTextField.setBounds(177, 201, 31, 26);
		panelFood.add(cokeCntTextField);
		
		sodaCntTextField = new JTextField();
		sodaCntTextField.setText("0");
		sodaCntTextField.setEditable(false);
		sodaCntTextField.setColumns(10);
		sodaCntTextField.setBounds(177, 230, 31, 26);
		panelFood.add(sodaCntTextField);
		
		beerCntTextField = new JTextField();
		beerCntTextField.setText("0");
		beerCntTextField.setEditable(false);
		beerCntTextField.setColumns(10);
		beerCntTextField.setBounds(177, 258, 31, 26);
		panelFood.add(beerCntTextField);
		
		chickenUpBtn = new JButton("+");
		chickenUpBtn.setBounds(213, 38, 25, 16);
		panelFood.add(chickenUpBtn);
		
		beefUpBtn = new JButton("+");
		beefUpBtn.setBounds(213, 67, 25, 16);
		panelFood.add(beefUpBtn);
		
		mixUpBtn = new JButton("+");
		mixUpBtn.setBounds(213, 95, 25, 16);
		panelFood.add(mixUpBtn);
		
		friedUpBtn = new JButton("+");
		friedUpBtn.setBounds(213, 123, 25, 16);
		panelFood.add(friedUpBtn);
		
		ringUpBtn = new JButton("+");
		ringUpBtn.setBounds(213, 151, 25, 16);
		panelFood.add(ringUpBtn);
		
		nachoUpBtn = new JButton("+");
		nachoUpBtn.setBounds(213, 179, 25, 16);
		panelFood.add(nachoUpBtn);
		
		cokeUpBtn = new JButton("+");
		cokeUpBtn.setBounds(213, 207, 25, 16);
		panelFood.add(cokeUpBtn);
		
		sodaUpBtn = new JButton("+");
		sodaUpBtn.setBounds(213, 235, 25, 16);
		panelFood.add(sodaUpBtn);
		
		beerUpBtn = new JButton("+");
		beerUpBtn.setBounds(213, 264, 25, 16);
		panelFood.add(beerUpBtn);
		
		chickenDownBtn = new JButton("-");
		chickenDownBtn.setBounds(243, 38, 25, 16);
		panelFood.add(chickenDownBtn);
		
		beefDownBtn = new JButton("-");
		beefDownBtn.setBounds(243, 67, 25, 16);
		panelFood.add(beefDownBtn);
		
		mixDownBtn = new JButton("-");
		mixDownBtn.setBounds(243, 95, 25, 16);
		panelFood.add(mixDownBtn);
		
		friedDownBtn = new JButton("-");
		friedDownBtn.setBounds(243, 123, 25, 16);
		panelFood.add(friedDownBtn);
		
		ringDownBtn = new JButton("-");
		ringDownBtn.setBounds(243, 151, 25, 16);
		panelFood.add(ringDownBtn);
		
		nachoDownBtn = new JButton("-");
		nachoDownBtn.setBounds(243, 179, 25, 16);
		panelFood.add(nachoDownBtn);
		
		cokeDownBtn = new JButton("-");
		cokeDownBtn.setBounds(243, 207, 25, 16);
		panelFood.add(cokeDownBtn);
		
		sodaDownBtn = new JButton("-");
		sodaDownBtn.setBounds(243, 235, 25, 16);
		panelFood.add(sodaDownBtn);
		
		beerDownBtn = new JButton("-");
		beerDownBtn.setBounds(243, 264, 25, 16);
		panelFood.add(beerDownBtn);
		
		panelTopping = new JPanel();
		panelTopping.setLayout(null);
		panelTopping.setBounds(309, 177, 450, 166);
		contentPane.add(panelTopping);
		
		lblTopping = new JLabel("Topping");
		lblTopping.setBounds(48, 6, 74, 16);
		panelTopping.add(lblTopping);
		
		panelFlavor = new JPanel();
		panelFlavor.setLayout(null);
		panelFlavor.setBounds(309, 44, 450, 121);
		contentPane.add(panelFlavor);
		
		lblFlavor = new JLabel("Flavor");
		lblFlavor.setBounds(210, 6, 48, 16);
		panelFlavor.add(lblFlavor);
		
		lblChickenMild = new JLabel("Mild");
		lblChickenMild.setBounds(8, 38, 34, 16);
		panelFlavor.add(lblChickenMild);
		
		lblBeefMild = new JLabel("Mild");
		lblBeefMild.setBounds(8, 66, 34, 16);
		panelFlavor.add(lblBeefMild);
		
		lblMixMild = new JLabel("Mild");
		lblMixMild.setBounds(8, 94, 34, 16);
		panelFlavor.add(lblMixMild);
		
		chickenMildCntTextField = new JTextField();
		chickenMildCntTextField.setEditable(false);
		chickenMildCntTextField.setText("0");
		chickenMildCntTextField.setBounds(42, 33, 31, 26);
		panelFlavor.add(chickenMildCntTextField);
		chickenMildCntTextField.setColumns(10);
		
		beefMildCntTextField = new JTextField();
		beefMildCntTextField.setEditable(false);
		beefMildCntTextField.setText("0");
		beefMildCntTextField.setBounds(42, 61, 31, 26);
		panelFlavor.add(beefMildCntTextField);
		beefMildCntTextField.setColumns(10);
		
		mixMildCntTextField = new JTextField();
		mixMildCntTextField.setEditable(false);
		mixMildCntTextField.setText("0");
		mixMildCntTextField.setBounds(42, 89, 31, 26);
		panelFlavor.add(mixMildCntTextField);
		mixMildCntTextField.setColumns(10);
		
		chickenMildUpBtn = new JButton("+");
		chickenMildUpBtn.setBounds(76, 38, 25, 16);
		panelFlavor.add(chickenMildUpBtn);
		
		chickenMildDownBtn = new JButton("-");
		chickenMildDownBtn.setBounds(106, 38, 25, 16);
		panelFlavor.add(chickenMildDownBtn);
		
		beefMildUpBtn = new JButton("+");
		beefMildUpBtn.setBounds(76, 67, 25, 16);
		panelFlavor.add(beefMildUpBtn);
		
		beefMildDownBtn = new JButton("-");
		beefMildDownBtn.setBounds(106, 67, 25, 16);
		panelFlavor.add(beefMildDownBtn);
		
		mixMildUpBtn = new JButton("+");
		mixMildUpBtn.setBounds(76, 95, 25, 16);
		panelFlavor.add(mixMildUpBtn);
		
		mixMildDownBtn = new JButton("-");
		mixMildDownBtn.setBounds(106, 95, 25, 16);
		panelFlavor.add(mixMildDownBtn);
		
		lblChickenSpicy = new JLabel("Spicy");
		lblChickenSpicy.setBounds(140, 38, 40, 16);
		panelFlavor.add(lblChickenSpicy);
		
		lblBeefSpicy = new JLabel("Spicy");
		lblBeefSpicy.setBounds(140, 66, 40, 16);
		panelFlavor.add(lblBeefSpicy);
		
		lblMixSpicy = new JLabel("Spicy");
		lblMixSpicy.setBounds(140, 94, 40, 16);
		panelFlavor.add(lblMixSpicy);
		
		chickenSpicyCntTextField = new JTextField();
		chickenSpicyCntTextField.setEditable(false);
		chickenSpicyCntTextField.setBounds(180, 33, 31, 26);
		panelFlavor.add(chickenSpicyCntTextField);
		chickenSpicyCntTextField.setText("0");
		chickenSpicyCntTextField.setColumns(10);
		
		beefSpicyCntTextField = new JTextField();
		beefSpicyCntTextField.setEditable(false);
		beefSpicyCntTextField.setText("0");
		beefSpicyCntTextField.setBounds(180, 61, 31, 26);
		panelFlavor.add(beefSpicyCntTextField);
		beefSpicyCntTextField.setColumns(10);
		
		mixSpicyCntTextField = new JTextField();
		mixSpicyCntTextField.setEditable(false);
		mixSpicyCntTextField.setText("0");
		mixSpicyCntTextField.setBounds(180, 89, 31, 26);
		panelFlavor.add(mixSpicyCntTextField);
		mixSpicyCntTextField.setColumns(10);
		
		lblChickenVerySpicy = new JLabel("Very Spicy");
		lblChickenVerySpicy.setBounds(281, 38, 70, 16);
		panelFlavor.add(lblChickenVerySpicy);
		
		chickenSpicyUpBtn = new JButton("+");
		chickenSpicyUpBtn.setBounds(214, 38, 25, 16);
		panelFlavor.add(chickenSpicyUpBtn);
		
		beefSpicyUpBtn = new JButton("+");
		beefSpicyUpBtn.setBounds(214, 67, 25, 16);
		panelFlavor.add(beefSpicyUpBtn);
		
		mixSpicyUpBtn = new JButton("+");
		mixSpicyUpBtn.setBounds(214, 95, 25, 16);
		panelFlavor.add(mixSpicyUpBtn);
		
		chickenSpicyDownBtn = new JButton("-");
		chickenSpicyDownBtn.setBounds(244, 38, 25, 16);
		panelFlavor.add(chickenSpicyDownBtn);
		
		beefSpicyDownBtn = new JButton("-");
		beefSpicyDownBtn.setBounds(244, 67, 25, 16);
		panelFlavor.add(beefSpicyDownBtn);
		
		mixSpicyDownBtn = new JButton("-");
		mixSpicyDownBtn.setBounds(244, 95, 25, 16);
		panelFlavor.add(mixSpicyDownBtn);
		
		lblBeefVerySpicy = new JLabel("Very Spicy");
		lblBeefVerySpicy.setBounds(281, 66, 70, 16);
		panelFlavor.add(lblBeefVerySpicy);
		
		lblMixVerySpicy = new JLabel("Very Spicy");
		lblMixVerySpicy.setBounds(281, 94, 70, 16);
		panelFlavor.add(lblMixVerySpicy);
		
		chickenVerySpicyCntTextField = new JTextField();
		chickenVerySpicyCntTextField.setEditable(false);
		chickenVerySpicyCntTextField.setText("0");
		chickenVerySpicyCntTextField.setBounds(350, 33, 31, 26);
		panelFlavor.add(chickenVerySpicyCntTextField);
		chickenVerySpicyCntTextField.setColumns(10);
		
		beefVerySpicyCntTextField = new JTextField();
		beefVerySpicyCntTextField.setEditable(false);
		beefVerySpicyCntTextField.setText("0");
		beefVerySpicyCntTextField.setBounds(350, 61, 31, 26);
		panelFlavor.add(beefVerySpicyCntTextField);
		beefVerySpicyCntTextField.setColumns(10);
		
		mixVerySpicyCntTextField = new JTextField();
		mixVerySpicyCntTextField.setEditable(false);
		mixVerySpicyCntTextField.setText("0");
		mixVerySpicyCntTextField.setBounds(350, 89, 31, 26);
		panelFlavor.add(mixVerySpicyCntTextField);
		mixVerySpicyCntTextField.setColumns(10);
		
		chickenVerySpicyUpBtn = new JButton("+");
		chickenVerySpicyUpBtn.setBounds(383, 38, 25, 16);
		panelFlavor.add(chickenVerySpicyUpBtn);
		
		beefVerySpicyUpBtn = new JButton("+");
		beefVerySpicyUpBtn.setBounds(383, 67, 25, 16);
		panelFlavor.add(beefVerySpicyUpBtn);
		
		mixVerySpicyUpBtn = new JButton("+");
		mixVerySpicyUpBtn.setBounds(383, 95, 25, 16);
		panelFlavor.add(mixVerySpicyUpBtn);
		
		chickenVerySpicyDownBtn = new JButton("-");
		chickenVerySpicyDownBtn.setBounds(413, 38, 25, 16);
		panelFlavor.add(chickenVerySpicyDownBtn);
		
		beefVerySpicyDownBtn = new JButton("-");
		beefVerySpicyDownBtn.setBounds(413, 67, 25, 16);
		panelFlavor.add(beefVerySpicyDownBtn);
		
		mixVerySpicyDownBtn = new JButton("-");
		mixVerySpicyDownBtn.setBounds(413, 95, 25, 16);
		panelFlavor.add(mixVerySpicyDownBtn);
		
		btnOrder = new JButton("Order");
		btnOrder.setBounds(642, 369, 117, 29);
		contentPane.add(btnOrder);
	}
}
