package view;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : KioskDevice.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class KioskDevice {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}
	
	public void showOrderResult()
	{
	
	}
		
	public void showRefundResult()
	{
	
	}

}
