//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : KitchenDisplay.java
//  @ Date : 2018-12-15
//  @ Author : 
//
//




public class KitchenDisplay
{
	public boolean refundACK;
	public void displayOrder()
	{
	
	}
	
	public void displayRefundReq()
	{
	
	}
	
	public void sendACK()
	{
	
	}
}
