package view;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Kiosk
//  @ File Name : KitchenDisplay.java
//  @ Date : 2018-12-16
//  @ Author : 
//
//

public class KitchenDisplay
{
	public boolean refundACK;
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}
	
	public void displayOrder()
	{
	
	}
	
	public void displayRefundReq()
	{
	
	}
	
	public void sendACK()
	{
	
	}
}
